remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: echoes of it | artist and author
description: Creating abstract digital art, writings, and other media.

show_downloads: "false"
google_analytics: 